version: "3.8"

services:
  back-end:
    container_name : back_end
    build: ./back-end
    environment:
      - DATABASE_URL=postgres://root:root@database:5432/ecocityguide
    depends_on:
      - database
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync
          path: ./back-end
          target: /app
        - action: rebuild
          path: back-end/package.json

  web-app:
    container_name : web_app
    build: ./web-app
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./web-app
          target: /app
        - action: rebuild
          path: web-app/package.json

  database:
    container_name : database
    image: postgres:15
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ecocityguide
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - 8080:8080

volumes:
  database-data:
