version: "3.8"

services:
  back-end:
    container_name : back_end_circul_app
    build: ./back-end
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
    depends_on:
      - database
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync
          path: ./back-end
          target: /app
        - action: rebuild
          path: back-end/package.json

  web-app:
    container_name : web_app_circul_app
    build: ./web-app
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./web-app
          target: /app
        - action: rebuild
          path: web-app/package.json

  database:
    container_name : postgres_circul_app
    image: postgres:15
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  database-data:
