services:
  back-end:
    image: JonasJallet/eco-deploy-back-end
    command: sh -c "npm run build && npm run start"
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - NODE_ENV=production
    depends_on:
      - database
    expose:
      - 4000

  web-app:
    image: JonasJallet/eco-deploy-web-app
    command: sh -c "npm run build && npm run start && npm run tailwind"
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  database:
    image: postgis/postgis:15-3.4
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  gateway:
    image: nginx
    depends_on:
      - back-end
      - web-app
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

volumes:
  database-data:
