services:
  back-end:
    container_name: back_end
    build: ./back-end
    environment:
      - DATABASE_URL=postgres://root:root@database:5432/ecocityguide
      - TEST_DATABASE_URL=postgres://postgres:password@test-database:5432/postgres
    depends_on:
      - database
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: ./back-end
          target: /app
        - action: rebuild
          path: back-end/package.json

  web-app:
    container_name: web_app
    build: ./web-app
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./web-app
          target: /app
        - action: rebuild
          path: web-app/package.json

  database:
    container_name: database
    image: postgis/postgis:15-3.4
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ecocityguide
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

  test-database:
    container_name: test-database
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_PASSWORD=password

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "8080:8080"

volumes:
  database-data:
