services:
  back-end:
    build:
      context: ./back-end
      target: ci
    environment:
      - TEST_DATABASE_URL=postgres://postgres:password@test-database:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - test-database
      - redis

  test-database:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
