services:
  back-end:
    image: jonasjallet/eco-deploy-server
    command: sh -c "npm run build"
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - NODE_ENV=production
    depends_on:
      database:
        condition: service_healthy
    expose:
      - 4000

  web-app:
    image: jonasjallet/eco-deploy-client
    command: sh -c "npm run next build"
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  database:
    image: postgis/postgis:15-3.4
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -U postgres

  gateway:
    image: nginx
    depends_on:
      - back-end
      - web-app
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

volumes:
  database-data:
