services:
  back-end:
    build:
      context: ./back-end
      target: ci
    environment:
      - TEST_DATABASE_URL=postgres://postgres:password@test-database:5432/postgres
    depends_on:
      - test-database

  test-database:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_PASSWORD=password

  redis:
    image: redis
