name: Format Fix on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  format-fix:
    name: Fix source code format with Prettier
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Prettier to fix format
        run: npm run format:fix

      - name: Check if changes exist
        id: check_changes
        run: |
          git diff --exit-code || echo "No changes to commit"

      - name: Commit changes
        if: steps.check_changes.outputs.code != '0'
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions (format-fix)"
          git commit -m "[AUTO] Fix source code format with Prettier"

      - name: Push changes
        if: steps.check_changes.outputs.code != '0'
        run: git push
