on: push

permissions:
  contents: write

jobs:
  ci-back-end:
    name: Build and test back-end
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
    steps:
      - uses: actions/checkout@v4
      - name: Wait for Redis to be ready
      - run: docker compose -f docker-compose.ci.back-end.yml up --build --exit-code-from back-end
